.<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> 
Time Elapsed: 0:00:07.889442
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\untitled2\lianxi\baidu.py", line 82, in <module>
    youjian.send_email(HtmlFile)
  File "C:\Users\Administrator\PycharmProjects\untitled2\lianxi\youjian.py", line 23, in send_email
    smtp.connect(smtpserver)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\untitled2\lianxi\demo_01.py", line 19, in <module>
    unittest.main(defaultTest='suite')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\main.py", line 159, in createTests
    self.module)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 205, in loadTestsFromName
    test = obj()
  File "C:\Users\Administrator\PycharmProjects\untitled2\lianxi\demo_01.py", line 14, in suite
    suite=unittest.TsetSuite()
AttributeError: module 'unittest' has no attribute 'TsetSuite'
..<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> 
Time Elapsed: 0:00:00
